./so_long maps/other-maps/20Hunt.ber
./so_long maps/other-maps/bigHunt.ber
./so_long maps/other-maps/capsuleClassic.ber
./so_long maps/other-maps/classic.ber
./so_long maps/other-maps/contestClassic.ber
./so_long maps/other-maps/labAA1.ber
./so_long maps/other-maps/labAA2.ber
./so_long maps/other-maps/labAA3.ber
./so_long maps/other-maps/labAA4.ber
./so_long maps/other-maps/labAA5.ber
./so_long maps/other-maps/mediumClassic.ber
./so_long maps/other-maps/mimapa.ber
./so_long maps/other-maps/minimaxClassic.ber
./so_long maps/other-maps/newmap.ber
./so_long maps/other-maps/oneHunt.ber
./so_long maps/other-maps/openClassic.ber
./so_long maps/other-maps/openHunt.ber
./so_long maps/other-maps/originalClassic.ber
./so_long maps/other-maps/ourLayout.ber
./so_long maps/other-maps/sixHunt.ber
./so_long maps/other-maps/smallClassic.ber
./so_long maps/other-maps/smallHunt.ber
./so_long maps/other-maps/testClassic.ber
./so_long maps/other-maps/trappedClassic.ber
./so_long maps/other-maps/trickyClassic.ber
